apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-rp-sales-app
  namespace: ns-retailpulse
data:
  application.yaml: |
    server:
      port: 8085

    auth:
      enabled: false
      origin: "http://localhost:4200"
      jwt:
        key:
          set:
            uri: http://app-iam:8081/oauth2/jwks

    spring:
      datasource:
        url: jdbc:mysql://mysql-rp-sales:3306/RPSalesDB
        username: root
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver

      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        
    inventory-service:
      url: http://svc-rp-inventory:8084

    logging:
      level:
        root: INFO
        org:
          springframework:
            security: TRACE
        com.retailpulse: DEBUG
      file:
        name: logs/rp-sales.log

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rp-sales
  namespace: ns-retailpulse
  labels:
    app: deploy-rp-sales  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-rp-sales
  template:
    metadata:
      labels:
        app: deploy-rp-sales
    spec:
      containers:
      - image: docker.io/casperyap/rp-sales-app:v0.1.0
        name: myapp        
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources: {}
      volumes:
      - name: config-volume
        configMap:
          name: cm-rp-sales-app

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: deploy-rp-sales
  name: svc-rp-sales
spec:
  selector:
    app: deploy-rp-sales
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
    nodePort: 30085
  type: NodePort